-- FunGerman `words` table. Column names are lowercase (Postgres folds unquoted
-- names), so the app aliases them back to camelCase in WORDS_SELECT
-- (src/supabase/supabaseClient.js).
create table if not exists public.words (
  id        bigint generated by default as identity primary key,
  pos       text not null check (pos in ('Nomen','Verb','Adjektiv','Adverb','Konjunktion','Präposition','Phrase')),
  level     text not null check (level in ('A1','A2','B1','B2','C1')),
  article   text check (article in ('der','die','das')),
  word      text not null,
  plural    text check (plural is null or plural <> ''), -- null = no plural; never blank
  synonymde text,
  en        text not null,
  synonymen text,
  ctxde     text not null,
  hl        text not null
);

-- Public read-only access; no auth needed to browse. Writes only via the
-- dashboard / SQL Editor (see seed.sql).
alter table public.words enable row level security;

drop policy if exists "Public read access" on public.words;
create policy "Public read access" on public.words
  for select to anon, authenticated using (true);
