// A1 mock vocabulary. Same shape as the Supabase `words` table.
//
// plural: full plural form; the same word again if unchanged (Brötchen → Brötchen);
//         null if the noun has no plural (Obst), and for non-nouns.
// hl:     exact substring of ctxDe to highlight. Separate parts with " ... "
//         for split separable verbs ("sehe ... an").
export const mockVocabulary = [
  {
    id: 1,
    word: 'an·sehen',
    pos: 'Verb',
    level: 'A1',
    article: null,
    plural: null,
    synonymDe: null,
    en: 'to watch, look at',
    synonymEn: null,
    ctxDe: 'Ich sehe mir den Film an.',
    hl: 'sehe ... an',
  },
  {
    id: 2,
    word: 'ein·kaufen',
    pos: 'Verb',
    level: 'A1',
    article: null,
    plural: null,
    synonymDe: null,
    en: 'to shop, go shopping',
    synonymEn: null,
    ctxDe: 'Am Samstag kaufe ich im Supermarkt ein.',
    hl: 'kaufe ... ein',
  },
  {
    id: 3,
    word: 'auf·stehen',
    pos: 'Verb',
    level: 'A1',
    article: null,
    plural: null,
    synonymDe: null,
    en: 'to get up',
    synonymEn: null,
    ctxDe: 'Ich stehe jeden Tag um sieben Uhr auf.',
    hl: 'stehe ... auf',
  },
  {
    id: 4,
    word: 'bekommen',
    pos: 'Verb',
    level: 'A1',
    article: null,
    plural: null,
    synonymDe: null,
    en: 'to get',
    synonymEn: 'to receive',
    ctxDe: 'Ich bekomme morgen ein Paket.',
    hl: 'bekomme',
  },
  {
    id: 5,
    word: 'Umzug',
    pos: 'Nomen',
    level: 'A1',
    article: 'der',
    plural: 'Umzüge',
    synonymDe: null,
    en: 'move (to a new home)',
    synonymEn: null,
    ctxDe: 'Der Umzug war sehr anstrengend.',
    hl: 'Umzug',
  },
  {
    id: 6,
    word: 'Wohnung',
    pos: 'Nomen',
    level: 'A1',
    article: 'die',
    plural: 'Wohnungen',
    synonymDe: null,
    en: 'apartment',
    synonymEn: 'flat',
    ctxDe: 'Unsere Wohnung hat drei Zimmer.',
    hl: 'Wohnung',
  },
  {
    id: 7,
    word: 'Brötchen',
    pos: 'Nomen',
    level: 'A1',
    article: 'das',
    plural: 'Brötchen',
    synonymDe: 'Semmel',
    en: 'bread roll',
    synonymEn: null,
    ctxDe: 'Morgens esse ich ein Brötchen mit Käse.',
    hl: 'Brötchen',
  },
  {
    id: 8,
    word: 'Schlüssel',
    pos: 'Nomen',
    level: 'A1',
    article: 'der',
    plural: 'Schlüssel',
    synonymDe: null,
    en: 'key',
    synonymEn: null,
    ctxDe: 'Ich finde meinen Schlüssel nicht.',
    hl: 'Schlüssel',
  },
  {
    id: 9,
    word: 'Obst',
    pos: 'Nomen',
    level: 'A1',
    article: 'das',
    plural: null,
    synonymDe: null,
    en: 'fruit',
    synonymEn: null,
    ctxDe: 'Ich kaufe jeden Samstag frisches Obst.',
    hl: 'Obst',
  },
  {
    id: 10,
    word: 'müde',
    pos: 'Adjektiv',
    level: 'A1',
    article: null,
    plural: null,
    synonymDe: null,
    en: 'tired',
    synonymEn: null,
    ctxDe: 'Nach der Arbeit bin ich immer müde.',
    hl: 'müde',
  },
  {
    id: 11,
    word: 'gern',
    pos: 'Adverb',
    level: 'A1',
    article: null,
    plural: null,
    synonymDe: null,
    en: 'like to (do something)',
    synonymEn: 'gladly',
    ctxDe: 'Ich trinke gern Kaffee.',
    hl: 'gern',
  },
  {
    id: 12,
    word: 'aber',
    pos: 'Konjunktion',
    level: 'A1',
    article: null,
    plural: null,
    synonymDe: null,
    en: 'but',
    synonymEn: null,
    ctxDe: 'Das Zimmer ist klein, aber gemütlich.',
    hl: 'aber',
  },
  {
    id: 13,
    word: 'neben',
    pos: 'Präposition',
    level: 'A1',
    article: null,
    plural: null,
    synonymDe: null,
    en: 'next to',
    synonymEn: null,
    ctxDe: 'Die Bäckerei ist neben der Bank.',
    hl: 'neben',
  },
  {
    id: 14,
    word: "Wie geht's?",
    pos: 'Phrase',
    level: 'A1',
    article: null,
    plural: null,
    synonymDe: 'Wie geht es dir?',
    en: 'How are you?',
    synonymEn: "How's it going?",
    ctxDe: "Hallo Anna, wie geht's?",
    hl: "wie geht's",
  },
];
